# Build and run tests
FROM maven:3.8.4-jdk-8 AS builder
WORKDIR /app
COPY . .
RUN mvn clean install -DskipTests=false

# run the application
FROM tomcat:9.0-jre8
COPY --from=builder /app/target/accenture-techhub-0.0.1-SNAPSHOT.war /usr/local/tomcat/webapps/accenture-techhub-0.0.1-SNAPSHOT.war
EXPOSE 8080
CMD ["catalina.sh", "run"]

